# action.yaml
name: 'pre-commit-dbt'
description: 'List of pre-commit hooks to ensure the quality of your dbt projects.'
branding:
  icon: 'anchor'
  color: 'blue'
inputs:
  command:
    description: 'pre-commit command'
    required: false
    default: 'run'
  option:
    description: 'pre-commit option'
    required: false
    default: '--all-files'
  files:
    description: 'pre-commit files'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command}}
    - ${{ inputs.option}}
    - ${{ inputs.files}}
